const dummyDetails = [
    {
      post_id: "1",
      type_id: "101",
      type_name: "Apartment",
      user_name: "John Doe",
      user_image: "user1.jpg",
      post_title: "Modern Apartment in City Center",
      post_description: "A spacious and modern apartment located in the heart of the city. Close to public transportation and shopping centers.",
      phone: "123-456-7890",
      address: "123 City Center, Metropolis",
      latitude: "40.7128",
      longitude: "-74.0060",
      purpose: "For Rent",
      bedrooms: "2",
      bathrooms: "2",
      area: "1200 sqft",
      furnishing: "Fully Furnished",
      amenities: "Gym, Pool, Parking",
      price: 2500,
      verified: "True",
      post_image: "apartment1.jpg",
      floor_plan_image: "floorplan1.jpg",
      total_views: 200,
      favourite: false,
      galleryList: ["gallery1.jpg", "gallery2.jpg", "gallery3.jpg"],
      relatedProperty: ["2", "3"]
    },
    {
      post_id: "2",
      type_id: "102",
      type_name: "House",
      user_name: "Emily Clark",
      user_image: "user2.jpg",
      post_title: "Cozy Cottage Near the Lake",
      post_description: "A beautiful cottage with breathtaking views of the lake. Perfect for a weekend getaway or a peaceful permanent residence.",
      phone: "321-654-0987",
      address: "456 Lakeside Drive, Tranquility",
      latitude: "36.7783",
      longitude: "-119.4179",
      purpose: "For Sale",
      bedrooms: "3",
      bathrooms: "2",
      area: "1500 sqft",
      furnishing: "Partially Furnished",
      amenities: "Private Dock, Large Yard",
      price: 350000,
      verified: "True",
      post_image: "house1.jpg",
      floor_plan_image: "floorplan2.jpg",
      total_views: 150,
      favourite: true,
      galleryList: ["house_gallery1.jpg", "house_gallery2.jpg", "house_gallery3.jpg"],
      relatedProperty: ["1", "3"]
    },
    {
      post_id: "3",
      type_id: "103",
      type_name: "Condo",
      user_name: "Michael Smith",
      user_image: "user3.jpg",
      post_title: "Luxury Condo with Skyline Views",
      post_description: "High in the sky, this luxury condo offers stunning views of the city skyline. Includes top-of-the-line amenities and finishes.",
      phone: "987-123-4567",
      address: "789 Skyline Boulevard, Metropolis",
      latitude: "34.0522",
      longitude: "-118.2437",
      purpose: "For Rent",
      bedrooms: "1",
      bathrooms: "1",
      area: "800 sqft",
      furnishing: "Fully Furnished",
      amenities: "Rooftop Pool, Fitness Center, Concierge",
      price: 3000,
      verified: "False",
      post_image: "condo1.jpg",
      floor_plan_image: "floorplan3.jpg",
      total_views: 250,
      favourite: false,
      galleryList: ["condo_gallery1.jpg", "condo_gallery2.jpg", "condo_gallery3.jpg"],
      relatedProperty: ["1", "2"]
    }
  ];
  
  module.exports = dummyDetails;
  