const data = {
    "REAL_ESTATE_APP": {
      "properties": [
        {
          "post_id": "19",
          "type_id": "101",
          "type_name": "Apartment",
          "user_name": "John Doe",
          "user_image": "https://example.com/user_images/user1.jpg",
          "post_title": "Vertillas",
          "post_description": "A luxurious apartment in Kharadi, Pune, offering state-of-the-art amenities and a comfortable living experience.",
          "phone": "123-456-7890",
          "address": "Kharadi, Pune",
          "latitude": "26.473094232435002",
          "longitude": "80.2927108452001",
          "purpose": "Rent",
          "bedrooms": "3",
          "bathrooms": "2",
          "location": { 
            "type": "Point", 
            "coordinates": [80.2927108452001, 26.473094232435002] // [longitude, latitude]
          },
          "area": "1500 sqft",
          "furnishing": "Fully Furnished",
          "amenities": "Gym, Pool, Parking",
          "price": 11000000,
          "verified": "True",
          "post_image": "https://envato.viaviweb.in/real_estate_app/upload/NewFolder/13.jpg",
          "floor_plan_image": "https://example.com/floor_plans/floorplan1.jpg",
          "total_views": "103",
          "favourite": false,
          "galleryList": ["https://envato.viaviweb.in/real_estate_app/upload/NewFolder/13.jpg"],
          "relatedProperty": ["17", "16", "15", "13"]
        },
        {
          "post_id": "17",
          "type_id": "102",
          "type_name": "House",
          "user_name": "Emily Clark",
          "user_image": "https://example.com/user_images/user2.jpg",
          "post_title": "Nageshwar City",
          "post_description": "Elegant house in Jamnagar Road, Rajkot, blending modern design with comfort, ideal for families seeking a peaceful living space.",
          "phone": "321-654-9870",
          "address": "Jamnagar Road, Rajkot",
          "latitude": " 26.46911",
          "longitude": "80.29445",
          "purpose": "Sale",
          "bedrooms": "4",
          "bathrooms": "3",
          "location": { 
            "type": "Point", 
            "coordinates": [80.29445, 26.46911] // [longitude, latitude]
          },
          "area": "2000 sqft",
          "furnishing": "Semi-Furnished",
          "amenities": "Private Garden, Garage",
          "price": 5000000,
          "verified": "True",
          "post_image": "https://envato.viaviweb.in/real_estate_app/upload/NewFolder/10.jpg",
          "floor_plan_image": "https://example.com/floor_plans/floorplan2.jpg",
          "total_views": "50",
          "favourite": false,
          "galleryList": ["https://envato.viaviweb.in/real_estate_app/upload/NewFolder/10.jpg"],
          "relatedProperty": ["19", "16", "15", "13"]
        },
        {
          "post_id": "16",
          "type_id": "103",
          "type_name": "Villa",
          "user_name": "Michael Bay",
          "user_image": "https://example.com/user_images/user3.jpg",
          "post_title": "Nilkanth Villa",
          "post_description": "Spacious villa in 150 Feet Ring Road, Rajkot, with a beautiful garden and luxurious amenities, perfect for high-end living.",
          "phone": "456-789-0123",
          "address": "150 Feet Ring Road, Rajkot",
          "latitude": "26.47675",
          "longitude": "80.29220",
          "purpose": "Rent",
          "bedrooms": "5",
          "bathrooms": "4",
          "location": { 
            "type": "Point", 
            "coordinates": [80.29220, 26.47675] // [longitude, latitude]
          },
          "area": "2500 sqft",
          "furnishing": "Partially Furnished",
          "amenities": "Swimming Pool, Large Patio",
          "price": 8000000,
          "verified": "True",
          "post_image": "https://envato.viaviweb.in/real_estate_app/upload/NewFolder/9.jpg",
          "floor_plan_image": "https://example.com/floor_plans/floorplan3.jpg",
          "total_views": "75",
          "favourite": true,
          "galleryList": ["https://envato.viaviweb.in/real_estate_app/upload/NewFolder/9.jpg"],
          "relatedProperty": ["19", "17", "15", "13"]
        },
        {
          "post_id": "15",
          "type_id": "104",
          "type_name": "Condominium",
          "user_name": "Alice Wonderland",
          "user_image": "https://example.com/user_images/user4.jpg",
          "post_title": "Akshar Heights",
          "post_description": "Modern condominium at Nana Mava, Rajkot, offering sleek design, rooftop amenities, and city views, ideal for urban professionals.",
          "phone": "789-012-3456",
          "address": "Nana Mava, Rajkot",
          "latitude": "26.47491",
          "longitude": "80.28973",
          "location": { 
            "type": "Point", 
            "coordinates": [80.28973, 26.47491] // [longitude, latitude]
          },
          "purpose": "Rent",
          "bedrooms": "2",
          "bathrooms": "2",
          "area": "1200 sqft",
          "furnishing": "Fully Furnished",
          "amenities": "Rooftop Pool, Fitness Center",
          "price": 6000000,
          "verified": "False",
          "post_image": "https://envato.viaviweb.in/real_estate_app/upload/NewFolder/8.jpg",
          "floor_plan_image": "https://example.com/floor_plans/floorplan4.jpg",
          "total_views": "90",
          "favourite": false,
          "galleryList": ["https://envato.viaviweb.in/real_estate_app/upload/NewFolder/8.jpg"],
          "relatedProperty": ["19", "17", "16", "13"]
        },
        {
          "post_id": "13",
          "type_id": "105",
          "type_name": "Townhouse",
          "user_name": "Greg House",
          "user_image": "https://example.com/user_images/user5.jpg",
          "post_title": "Alpha Mangalam",
          "post_description": "Charming townhouse on Nana Mava Road, Rajkot, with intimate community vibes and green spaces, suitable for families or retirees.",
          "phone": "012-345-6789",
          "address": "Nana Mava Road, Rajkot",
          "latitude": "26.47536",
          "longitude": "80.29613",
          "purpose": "Sale",
          "bedrooms": "3",
          "bathrooms": "3",
          "location": { 
            "type": "Point", 
            "coordinates": [80.29613, 26.47536] // [longitude, latitude]
          },
          "area": "1800 sqft",
          "furnishing": "Unfurnished",
          "amenities": "Community Garden, Playground",
          "price": 7000000,
          "verified": "True",
          "post_image": "https://envato.viaviweb.in/real_estate_app/upload/NewFolder/6.jpg",
          "floor_plan_image": "https://example.com/floor_plans/floorplan5.jpg",
          "total_views": "65",
          "favourite": true,
          "galleryList": ["https://envato.viaviweb.in/real_estate_app/upload/NewFolder/6.jpg"],
          "relatedProperty": ["19", "17", "16", "15"]
        },

        {
          "post_id": "20",
          "type_id": "106",
          "type_name": "Studio",
          "user_name": "Outside Circle",
          "user_image": "https://example.com/user_images/user6.jpg",
          "post_title": "Zen Studios",
          "post_description": "Cozy studio apartments in a prime location, perfect for singles or young couples starting out.",
          "phone": "987-654-3210",
          "address": "Specific Address 1",
          "latitude": "26.48254",
          "longitude": "80.29316",
          "purpose": "Rent",
          "bedrooms": "1",
          "bathrooms": "1",
          "location": { 
            "type": "Point", 
            "coordinates": [80.29316, 26.48254]
          },
          "area": "500 sqft",
          "furnishing": "Fully Furnished",
          "amenities": "Laundry, High-Speed Internet",
          "price": 2000000,
          "verified": "True",
          "post_image": "https://example.com/upload/NewFolder/studio1.jpg",
          "floor_plan_image": "https://example.com/floor_plans/studio_plan1.jpg",
          "total_views": "30",
          "favourite": false,
          "galleryList": ["https://example.com/upload/NewFolder/studio1.jpg"],
          "relatedProperty": ["19", "17", "16"]
        },
        {
          "post_id": "21",
          "type_id": "107",
          "type_name": "Loft",
          "user_name": "Outside Circle",
          "user_image": "https://example.com/user_images/user7.jpg",
          "post_title": "Urban Lofts",
          "post_description": "Modern loft apartments with open floor plans, high ceilings, and plenty of natural light.",
          "phone": "123-987-6540",
          "address": "Specific Address 2",
          "latitude": "26.47813",
          "longitude": "80.29717",
          "purpose": "Sale",
          "bedrooms": "2",
          "bathrooms": "2",
          "location": { 
            "type": "Point", 
            "coordinates": [80.29717, 26.47813]
          },
          "area": "800 sqft",
          "furnishing": "Semi-Furnished",
          "amenities": "Elevator, Security",
          "price": 3000000,
          "verified": "True",
          "post_image": "https://example.com/upload/NewFolder/loft1.jpg",
          "floor_plan_image": "https://example.com/floor_plans/loft_plan1.jpg",
          "total_views": "45",
          "favourite": true,
          "galleryList": ["https://example.com/upload/NewFolder/loft1.jpg"],
          "relatedProperty": ["20", "19", "17"]
        },
        {
          "post_id": "22",
          "type_id": "108",
          "type_name": "Penthouse",
          "user_name": "Outside Circle",
          "user_image": "https://example.com/user_images/user8.jpg",
          "post_title": "Skyline Penthouses",
          "post_description": "Luxury penthouses offering breathtaking views and upscale amenities, for those who demand the best.",
          "phone": "654-321-9870",
          "address": "Specific Address 3",
          "latitude": "26.49231",
          "longitude": "80.32740",
          "purpose": "Rent",
          "bedrooms": "4",
          "bathrooms": "3",
          "location": { 
            "type": "Point", 
            "coordinates": [80.32740, 26.49231]
          },
          "area": "2000 sqft",
          "furnishing": "Fully Furnished",
          "amenities": "Private Rooftop, Pool, Gym",
          "price": 10000000,
          "verified": "True",
          "post_image": "https://example.com/upload/NewFolder/penthouse1.jpg",
          "floor_plan_image": "https://example.com/floor_plans/penthouse_plan1.jpg",
          "total_views": "70",
          "favourite": true,
          "galleryList": ["https://example.com/upload/NewFolder/penthouse1.jpg"],
          "relatedProperty": ["21", "20", "19"]
        }
        

      ],
      "total_records": 5,
      "load_more": false,
      "status_code": 200
    }
  };
  
  module.exports = data;
  