const dummydata = {
  "REAL_ESTATE_APP": {
      "detailList": [
          {
              post_id: "1",
              type_id: "101",
              type_name: "Apartment",
              user_name: "John Doe",
              user_image: "user1.jpg",
              post_title: "Modern Apartment in City Center",
              post_description: "A spacious and modern apartment located in the heart of the city. Close to public transportation and shopping centers.",
              phone: "123-456-7890",
              address: "123 City Center, Metropolis",
              latitude: "40.7128",
              longitude: "-74.0060",
              purpose: "For Rent",
              bedrooms: "2",
              bathrooms: "2",
              area: "1200 sqft",
              furnishing: "Fully Furnished",
              amenities: "Gym, Pool, Parking",
              price: 2500,
              verified: "True",
              post_image: "apartment1.jpg",
              floor_plan_image: "floorplan1.jpg",
              total_views: 200,
              favourite: false,
              galleryList: ["gallery1.jpg", "gallery2.jpg", "gallery3.jpg"],
              relatedProperty: ["2", "3"]
          },
          {
              post_id: "2",
              type_id: "102",
              type_name: "House",
              user_name: "Emily Clark",
              user_image: "user2.jpg",
              post_title: "Charming House in Suburbs",
              post_description: "A beautiful and cozy house located in a quiet neighborhood. Perfect for families looking for a peaceful retreat.",
              phone: "321-654-0987",
              address: "456 Suburb Lane, Quietville",
              latitude: "40.6892",
              longitude: "-74.0445",
              purpose: "For Sale",
              bedrooms: "4",
              bathrooms: "3",
              area: "2000 sqft",
              furnishing: "Partially Furnished",
              amenities: "Large Backyard, Garage, Deck",
              price: 450000,
              verified: "True",
              post_image: "house1.jpg",
              floor_plan_image: "floorplan2.jpg",
              total_views: 150,
              favourite: true,
              galleryList: ["house_gallery1.jpg", "house_gallery2.jpg"],
              relatedProperty: ["1", "3"]
          },
          {
              post_id: "3",
              type_id: "103",
              type_name: "Condo",
              user_name: "Michael Smith",
              user_image: "user3.jpg",
              post_title: "Luxury Condo with City Views",
              post_description: "High-rise luxury condo with stunning views of the city skyline. Includes state-of-the-art amenities for a comfortable urban living experience.",
              phone: "987-123-4567",
              address: "789 Downtown St, Metropolis",
              latitude: "40.7484",
              longitude: "-73.9857",
              purpose: "For Rent",
              bedrooms: "1",
              bathrooms: "1",
              area: "900 sqft",
              furnishing: "Fully Furnished",
              amenities: "Doorman, Fitness Center, Rooftop Pool",
              price: 3000,
              verified: "False",
              post_image: "condo1.jpg",
              floor_plan_image: "floorplan3.jpg",
              total_views: 250,
              favourite: false,
              galleryList: ["condo_gallery1.jpg", "condo_gallery2.jpg", "condo_gallery3.jpg"],
              relatedProperty: ["1", "2"]
          }
      ],
      "status_code": 200
  }
};

module.exports = data;
